import UIKit
import SwiftUI
import os

// ══════════════════════════════════════════════════════════════════
// MARK: - AlternateIconService
//
// Plumbs `UIApplication.setAlternateIconName(_:completionHandler:)` into
// a small @Observable surface so SwiftUI screens (e.g. profile, in-app
// event detail, onboarding to seasonal challenges) can switch the home
// screen icon with a single binding.
//
// Asset-catalog requirements (to be wired up in `Assets.xcassets`):
//
//   AppIcon.appiconset (default — already shipping)
//   AlternateIcons:
//     • plastic-free-july     (June–August 2026 challenge season)
//     • holiday-pantry-hero   (December 2026 challenge season)
//     • world-food-day        (October 16 single-day event)
//     • freshli-pride         (year-round, opt-in)
//
// Each alternate icon must include light, dark, and tinted variants
// for parity with the main icon — see `DynamicIconLayers.swift` for
// the source-of-truth multi-layer composition we render and export.
//
// Info.plist must declare `CFBundleAlternateIcons`. Add this keyed
// dictionary to the main target's Info.plist:
//
//   <key>CFBundleIcons</key>
//   <dict>
//       <key>CFBundleAlternateIcons</key>
//       <dict>
//           <key>plastic-free-july</key>
//           <dict>
//               <key>CFBundleIconFiles</key>
//               <array><string>plastic-free-july</string></array>
//               <key>UIPrerenderedIcon</key>
//               <false/>
//           </dict>
//           ...
//       </dict>
//   </dict>
//
// (The actual Info.plist for Freshli is generated by Xcode build
// settings — these keys should be added through the target's Build
// Settings → Info → Bundle Icons section, NOT pasted into the synced
// Info.plist file directly.)
// ══════════════════════════════════════════════════════════════════

@Observable @MainActor
final class AlternateIconService {
    static let shared = AlternateIconService()

    private let logger = Logger(subsystem: "com.freshli.app", category: "AlternateIcon")

    /// All known alternate icon identifiers.
    enum Icon: String, CaseIterable, Identifiable, Sendable {
        case `default` = ""
        case plasticFreeJuly = "plastic-free-july"
        case holidayPantryHero = "holiday-pantry-hero"
        case worldFoodDay = "world-food-day"
        case freshliPride = "freshli-pride"

        var id: String { rawValue }

        /// Localised display name for settings rows.
        var displayName: LocalizedStringKey {
            switch self {
            case .default:           return "Freshli (Default)"
            case .plasticFreeJuly:   return "Plastic Free July"
            case .holidayPantryHero: return "Holiday Pantry Hero"
            case .worldFoodDay:      return "World Food Day"
            case .freshliPride:      return "Freshli Pride"
            }
        }

        /// SF Symbol that represents the icon in pickers.
        var previewSymbol: String {
            switch self {
            case .default:           return "leaf.fill"
            case .plasticFreeJuly:   return "drop.degreesign"
            case .holidayPantryHero: return "snowflake"
            case .worldFoodDay:      return "globe.europe.africa.fill"
            case .freshliPride:      return "rainbow"
            }
        }
    }

    /// Whether the host platform supports alternate icons.
    ///
    /// `UIApplication.shared.supportsAlternateIcons` is the system-level
    /// check (true on iOS 10.3+). Even when that is `true`, alternate
    /// icons only WORK if the bundle's `Info.plist` declares
    /// `CFBundleAlternateIcons` entries pointing to real `.appiconset`
    /// files. While the seasonal-icon PNGs are still being authored,
    /// the `CFBundleAlternateIcons` block in `Info.plist` is commented
    /// out — the API surface stays in place but `isSupported` correctly
    /// reports `false` so settings UI can hide the picker.
    ///
    /// Once the PNGs land and the `Info.plist` block is uncommented,
    /// this returns `true` automatically with no Swift change required.
    var isSupported: Bool {
        guard UIApplication.shared.supportsAlternateIcons else { return false }
        let icons = Bundle.main.object(forInfoDictionaryKey: "CFBundleIcons") as? [String: Any]
        let alternate = icons?["CFBundleAlternateIcons"] as? [String: Any]
        return !(alternate?.isEmpty ?? true)
    }

    /// The currently-active icon, or `.default` if none has been set.
    private(set) var current: Icon = {
        let raw = UIApplication.shared.alternateIconName ?? ""
        return Icon(rawValue: raw) ?? .default
    }()

    /// Switch to a new alternate icon. The system shows a confirmation
    /// alert on the user's behalf — we do not need to confirm in-app.
    func setIcon(_ icon: Icon) async {
        guard isSupported else {
            logger.warning("Alternate icons not supported on this device.")
            return
        }
        let target: String? = (icon == .default) ? nil : icon.rawValue
        do {
            try await UIApplication.shared.setAlternateIconName(target)
            current = icon
            logger.info("Set alternate icon to \(icon.rawValue, privacy: .public)")
        } catch {
            logger.error("setAlternateIconName failed: \(error.localizedDescription, privacy: .public)")
        }
    }

    /// Suggest a seasonal icon based on the current calendar date.
    /// Used by the in-app event detail to offer a one-tap icon change
    /// when the user opts in to a challenge.
    func suggestSeasonalIcon(for date: Date = Date()) -> Icon? {
        let cal = Calendar(identifier: .gregorian)
        let month = cal.component(.month, from: date)
        let day = cal.component(.day, from: date)
        switch (month, day) {
        case (6, 25...30), (7, _), (8, 1...10):
            return .plasticFreeJuly
        case (10, 16):
            return .worldFoodDay
        case (12, 18...31):
            return .holidayPantryHero
        default:
            return nil
        }
    }
}
