#!/bin/bash

# Freshli Build Fix Script
# This script cleans your Xcode project and helps identify issues

echo "🔧 Freshli Build Fix Script"
echo "=========================="
echo ""

# Step 1: Clean DerivedData
echo "Step 1: Cleaning DerivedData..."
rm -rf ~/Library/Developer/Xcode/DerivedData/Freshli-*
echo "✅ DerivedData cleaned"
echo ""

# Step 2: Instructions for Xcode
echo "Step 2: NOW DO THESE STEPS IN XCODE:"
echo "===================================="
echo ""
echo "1. CLOSE Xcode if it's open (⌘Q)"
echo "2. REOPEN Xcode"
echo "3. Click the blue 'Freshli' project icon (top of left sidebar)"
echo "4. Click 'Freshli' under TARGETS"
echo "5. Click 'Build Phases' tab"
echo "6. Click to expand 'Compile Sources'"
echo ""
echo "7. REMOVE DUPLICATES - Delete the second occurrence of:"
echo "   - RecipesView.swift"
echo "   - PSColors.swift"
echo "   - WeeklyWrapView.swift"
echo "   - PSSpacing.swift"
echo "   - AppSupabase.swift"
echo "   - Date+Extensions.swift"
echo "   - ProfileView.swift"
echo "   - CommunityView.swift"
echo "   - FreshliApp.swift"
echo "   - AddItemView.swift"
echo "   - View+Extensions.swift"
echo "   - FreshliDetailView.swift"
echo "   - PSShimmerView.swift"
echo "   - OfflineSyncQueue.swift"
echo "   - PSHaptics.swift"
echo "   - PSMotion.swift"
echo "   - PSEmptyState.swift"
echo "   - NetworkMonitor.swift"
echo "   - PSLayout.swift"
echo "   - PSLogger.swift"
echo ""
echo "8. MOVE DESIGN SYSTEM FILES TO TOP"
echo "   Drag these files to the TOP of the list:"
echo "   1. PSColors.swift (drag to position #1)"
echo "   2. PSSpacing.swift (drag to position #2)"
echo "   3. PSLayout.swift (drag to position #3)"
echo "   4. PSMotion.swift (drag to position #4)"
echo ""
echo "9. Press ⌘B to build"
echo ""
echo "=========================="
echo "✅ DerivedData is now clean!"
echo "📝 Follow the steps above in Xcode to complete the fix."
echo ""
